version: '3'
services:
  web:
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
      env_file:
        - .env
      volumes:
        - ./app:/app
      ports:
        - "3000:3000"
      depends_on:
        -
